site_name: DanielChou的異想世界
site_url: https://danielchou.github.io
use_directory_urls: true
docs_dir: docs
site_dir: site

nav:
  - 首頁: index.md
  - 關於我: aboutme.md
  - 作品集: portfolio.md

theme:
  name: material
  custom_dir: overrides
  logo: assets/logo.png
  favicon: assets/images/favicon.png
  icon:
    logo: material/library
  language: zh-TW
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.prune
    - navigation.indexes
    - navigation.top
    - toc.follow
    - toc.integrate
